Repository ncpi-fhir/ncpi-api-fhir-service, pull requests merged in 2021-05, with the labels that each got.

#29 🔧 Added additional ssl
  Jenkinsfile
Labels: devops

#30 ⬆️ Upgrade to 2021.02.R05
  Dockerfile
  README.md
  docker-compose.yml
  scripts/update_smilecdr.sh
Labels: feature

#31 🏷 Release 0.4.0
  CHANGELOG.md
Labels: release
